## NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 sevens

In [10]:
np.ones(10)*7

array([1., 1., 1., 1., 1., 1., 1.])

#### Create an array of the integers from 20 to 60

In [9]:
np.arange(20,61)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60])

#### Create an array of all the even integers from 20 to 60 

In [17]:
np.arange(20,61,2)

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58, 60])

#### Create a 4x4 matrix with values ranging from 0 to 15

In [18]:
np.arange(0,16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### Create a 4x4 identity matrix

In [23]:
np.identity(4) #or
# np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [29]:
np.random.rand(1)

array([0.70696008])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [33]:
np.random.randn(25)

array([ 0.60957467, -0.09740901, -1.13307894,  0.37873269,  0.52223927,
       -0.1945726 , -0.37662656,  1.6293257 , -0.18581914,  1.0425744 ,
        0.74964146, -0.03239183, -0.70411458, -0.68888563,  1.82319746,
        1.51795787, -0.08264861,  0.75141909,  0.7388305 , -0.11511619,
        0.2410518 , -0.27773299, -0.02865826, -0.92114988,  0.65010924])

#### Create the following matrix:

In [36]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 2:

In [38]:
np.linspace(0,2,20)

array([0.        , 0.10526316, 0.21052632, 0.31578947, 0.42105263,
       0.52631579, 0.63157895, 0.73684211, 0.84210526, 0.94736842,
       1.05263158, 1.15789474, 1.26315789, 1.36842105, 1.47368421,
       1.57894737, 1.68421053, 1.78947368, 1.89473684, 2.        ])

## Numpy Indexing and Selection

create a matrix with 25 elements(1-25) and name it mat

In [40]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

access element with value = 20

In [54]:
mat[3,4] #or
# mat[3][4]

20

In [72]:
#WRITE CODE HERE to Access value 2,7,12
#BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T BE ABLE TO SEE THE OUTPUT ANY MORE



In [73]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [78]:
#write code here acess the values shown in the output
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [79]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [81]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [86]:
np.sum(mat ,axis = 0)   # 0 means Columns and 1 means Row

array([55, 60, 65, 70, 75])