# Creating numpy array for 1D 

In [18]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# User input 

In [4]:
import numpy as np

In [8]:
a = []
n = int(input('Enter a Size :'))
for i in range(n):
    val = int(input("Enter the Value :"))
    a.append(val)
    
myarr = np.array(a)
myarr

Enter a Size :5
Enter the Value :1
Enter the Value :2
Enter the Value :3
Enter the Value :4
Enter the Value :5


array([1, 2, 3, 4, 5])

# Create numpy array for 2D 

In [30]:
import numpy as np
a = [[1,2,3], [4,5,6], [7,8,9]]
myarr = np.array(a)
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Create numpy array for 3D 

In [29]:
import numpy as np
a = [[[1,2,3,4,5], [6,7,8,9,10],[11,12,13,14,15]]]
myarr = np.array(a)
myarr

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

<!--  -->


# Numpy Functions 

In [79]:
# ones Func

import numpy as np
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [44]:
# zeros func

import numpy as np
arr = np.zeros(4)
arr

array([0., 0., 0., 0.])

In [51]:
# eye func

import numpy as np
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
# diag func

import numpy as np
arr = np.diag([5,2,4,5])
arr

array([[5, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [68]:
# randint func

import numpy as np
arr = np.random.randint(1,10,5)
arr

array([8, 3, 7, 4, 8])

In [77]:
# rand func

import numpy as np
arr = np.random.rand(5)
arr

array([0.79397145, 0.38249065, 0.56752463, 0.61691448, 0.60375105])

In [80]:
# randn func

import numpy as np
arr = np.random.randn(5)
arr

array([-0.79146625,  0.24878497,  0.72565113,  2.243285  ,  1.03350552])